# Model Selection 모듈

- 훈련/ 테스트 데이터로 분리하지 않고 머신러닝 수행

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

In [2]:
iris = load_iris()
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(iris.data, iris.target)
dtc.score(iris.data, iris.target)

1.0

- cross_validate() : 교차 검증, cv=5 가 디폴트

In [3]:
from sklearn.model_selection import cross_validate
dtc = DecisionTreeClassifier()
cross_validate(dtc, iris.data, iris.target) 

{'fit_time': array([0.00099039, 0.        , 0.        , 0.        , 0.        ]),
 'score_time': array([0.        , 0.00099707, 0.00099802, 0.00099611, 0.00099754]),
 'test_score': array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])}

- cross_val_score()

In [4]:
from sklearn.model_selection import cross_val_score
cross_val_score(dtc, iris.data, iris.target, scoring='accuracy', cv=5)

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [5]:
cross_val_score(dtc, iris.data, iris.target, scoring='accuracy',cv=3)

array([0.98, 0.94, 0.98])

- GridSearchCV 클래스 : 하이퍼 파라메터 튜닝 + 교차검증

In [6]:
# Train/Tes dataset 분리

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

In [8]:
# 분류기와 그에 해당하는 하이퍼 파라메터
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.get_params()

# 'max_depth', 'min_impurity_split' 이 자주 사용됨


{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [10]:
# 자주 사용되는 걸 dict의 형태로 만들어주기

params ={
    'max_depth' : [2,3,4,5,6],
    'min_samples_split' : [2,3,4]
}

In [12]:
# 위에거를 grid 객체로 만들어줌
from sklearn.model_selection import GridSearchCV

grid_dt = GridSearchCV(
    dtc, param_grid=params, scoring='accuracy', cv=5
)

In [13]:
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [14]:
#최적의 parameter
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 2}

여기서 부터 drop



2) 훈련 / 테스트 데이터셋 분리

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, stratify=wine.target, test_size=0.2, radom_state=2021
)

NameError: name 'wine' is not defined

In [17]:
import numpy as np 
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

3) GirdSearchCV를 통해서 

- DecisionTreeClassifier 또는 SVC 를 선택해서 
- 어떤 파라미터 일 때 최선의 모델이 되는지를 파악하고
- 그 때의 성능을 평가함

In [19]:
import warnings 
warnings.filterwarnings('ignore')

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

- Decision Tree

In [22]:
dtc = DecisionTreeClassifier(random_state=2021) 
params = {
        'max_depth' : [2,3,4,5,6],
    'min_samples_split' : [2,3,4]
}


In [23]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=5)
grid_dt.fit(X_train, y_train)
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 2}

In [24]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.9

- Support Vecotr Machine 

In [25]:
svc = SVC(random_state=2021)
paramas = {'c':[0.01, 0.1, 1, 10, 100]}

In [27]:
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

ValueError: Invalid parameter max_depth for estimator SVC(random_state=2021). Check the list of available parameters with `estimator.get_params().keys()`.