In [1]:
import numpy as np
import pandas as pd


- 데ㅣ터 전처리

In [3]:
df = pd.read_csv('pima-indians-diabetes.csv', skiprows=9)
df.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [4]:
df[1].head()

KeyError: 1

In [5]:
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)
df.columns =['P','G', 'BP','S','I','BMI','D','Age','Class']
df.head()

P    G  BP   S    I   BMI      D  Age  Class
0  1   85  66  29    0  26.6  0.351   31      0
1  8  183  64   0    0  23.3  0.672   32      1
2  1   89  66  23   94  28.1  0.167   21      0
3  0  137  40  35  168  43.1  2.288   33      1
4  5  116  74   0    0  25.6  0.201   30      0

In [6]:
df.index[:5]

RangeIndex(start=0, stop=5, step=1)

In [19]:
# 결측치 데이터가 있는지 확인
df.isna().sum()

P        0
G        0
BP       0
S        0
I        0
BMI      0
D        0
Age      0
Class    0
dtype: int64

In [8]:
X = df.iloc[:, :-1]
X.head()

# 데이터 프레임을 슬라이싱하면 여전히 데이터 프레임이다

P    G  BP   S    I   BMI      D  Age
0  1   85  66  29    0  26.6  0.351   31
1  8  183  64   0    0  23.3  0.672   32
2  1   89  66  23   94  28.1  0.167   21
3  0  137  40  35  168  43.1  2.288   33
4  5  116  74   0    0  25.6  0.201   30

In [10]:
X = df.iloc[:,:-1].values
type(X)

# values : 데이터 프레임을 numpy로 가져온다

numpy.ndarray

In [21]:
# 아까는 정수였는데 values 처리 하고 난 뒤 실수로 바뀜
# 데이터 프레임은 컬럼 단위로 동일한 타입
# numpy가 array 되는 순간 실수로 된다 : vlues 다는 순간 다같이 변환되는 것 
# 더 많은 데이터를 표시할 수 있기 때문에 정수-> 실수로 바뀌는 것

X[:5]

array([[1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01],
       [5.000e+00, 1.160e+02, 7.400e+01, 0.000e+00, 0.000e+00, 2.560e+01,
        2.010e-01, 3.000e+01]])

In [22]:
# 여러가지 방법으로 y값을 취할 수 있음

y = df['Class'].values
y = df.Class.values
y = df.iloc[:, -1].values


In [23]:
X.shape. y.shape

AttributeError: 'tuple' object has no attribute 'y'

- 참고 사항

In [32]:
df2 = pd.DataFrame(np.arange(25), reshape(5,5), Index=list('abcde'), columns=list('vwxyz'))
df2

NameError: name 'reshape' is not defined

In [25]:
df2['v']['c'] = np.nan
df2.z[3] = np.nan
df2

NameError: name 'df2' is not defined

In [27]:
df2.isna()

# 모든게 False고 NaN값이 True가 됨
# 만약 수가 많아진다면? -> python에는 False =0, True =1로 바뀐다

NameError: name 'df2' is not defined

In [29]:
df.insa().sum()

#이렇게 해서 숫자가 나온 부분이 결측치가 나왔다고 생각하면 된다

AttributeError: 'DataFrame' object has no attribute 'insa'

In [30]:
df2.insa().sum().sum()

# 2번 해버림ㅋ

NameError: name 'df2' is not defined

- Train / Test dataset으로 분리

In [35]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.2, random_state=2021
)

In [36]:
np.unique(y, return_counts=True)


(array([0, 1], dtype=int64), array([500, 267], dtype=int64))

In [37]:
np.unique(y_train, return_counts=True)

(array([0, 1], dtype=int64), array([400, 213], dtype=int64))

- GrideSearchCV, DecisionTreeClassifier

In [38]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
params = {
    'max_depth' : [2,3,4,5,6],
    'min_samples_split' : [2,3,4]
} 

In [39]:
from sklearn.model_selection import GridSearchCV
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=5)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [41]:
grid_dt.best_params_

# 언더바(_)는 속성값을 나타낼 때 쓰인다

{'max_depth': 2, 'min_samples_split': 2}

In [43]:
grid_dt.best_estimator_.score(X_test, y_test)

0.7597402597402597

In [44]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.7597402597402597

- 실제 적용

In [45]:
X_test[10], y_test[10]

(array([ 12.   , 100.   ,  84.   ,  33.   , 105.   ,  30.   ,   0.488,
         46.   ]),
 0)

In [54]:
test_data = X_test[10].reshape(1,-1)


In [55]:
pred = best_dt.predict(test_data)
pred

# 실제 원하는값

array([0], dtype=int64)

In [56]:
print('양성' if pred[0] == 1 else '음성')

# 보통은 3항 연산자를 사용하여 결과 도출

음성


In [57]:
# 이거는 너무 길어서 잘 사용 안 함
if pred[0] == 1:
    print('양성')
else :
    print('음성')

음성
