# 주성분 (PCA :Principal Component Analysis) 분석

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Iris 데이터 차원 축소

In [2]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [9]:
from sklearn.preprocessing import StandardScaler
iris_std = StandardScaler().fit_transform(iris.data)
iris_std[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

- PCA 객체 생성

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2) # 2개의 차원으로 만들 것이다

In [6]:
iris_pca = pca.fit_transform(iris_std)
iris_pca[:5]

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538]])

In [10]:
pca.explained_variance_ratio_

# 데이터의 73퍼  # 데이터의 23퍼
# 총 약 96프로의 데이터를 보여준다

array([0.72962445, 0.22850762])

- PCA 전후 분류 비교

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


In [12]:
# 원본 데이이터로 분류

X_trin, X_test, y_train, y_test : train_test_split(
    iris.data, iris.target, stratify=iris.target, ranom_state=2021
)
rfc = RandomForestClassifier(random_state=2021)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_)

SyntaxError: only single target (not tuple) can be annotated (<ipython-input-12-4080d06b0a9f>, line 3)

In [13]:
#PCA 데이터로 분류 

- 데이터 시각화